-- Flyway initial schema script
create table ai_conversation (created_at datetime(6), id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, session_id varchar(255) not null, primary key (id)) engine=InnoDB;
create table ai_conversation_message (conversation_id bigint not null, created_at datetime(6), id bigint not null auto_increment, role varchar(20) not null, content tinytext not null, primary key (id)) engine=InnoDB;
create table ai_tool_execution (success bit not null, conversation_id bigint not null, created_at datetime(6), id bigint not null auto_increment, tool_name varchar(255) not null, tool_arguments LONGTEXT, tool_response LONGTEXT, primary key (id)) engine=InnoDB;
create table cart (created_at datetime(6) not null, id bigint not null auto_increment, updated_at datetime(6), user_id bigint not null, primary key (id)) engine=InnoDB;
create table cart_item (quantity integer not null, cart_id bigint not null, id bigint not null auto_increment, product_id bigint not null, primary key (id)) engine=InnoDB;
create table dead_letter_notification (failed_at datetime(6) not null, delivery_id binary(16) not null, id binary(16) not null, reason varchar(255) not null, primary key (id)) engine=InnoDB;
create table g_user_session (created_by bigint, created_date datetime(6) not null, last_activity_timestamp datetime(6), refresh_token_expiry_time datetime(6) not null, updated_by bigint, updated_date datetime(6), user_session_id bigint not null auto_increment, usr_rid bigint not null, status varchar(20) not null, refresh_token_hash varchar(255) not null, primary key (user_session_id)) engine=InnoDB;
create table notification_delivery (retry_count integer not null, created_at datetime(6) not null, last_attempt_at datetime(6), event_id binary(16) not null, id binary(16) not null, error_message varchar(1000), channel varchar(255) not null, recipient_id varchar(255) not null, status varchar(255) not null, primary key (id)) engine=InnoDB;
create table notification_event (created_at datetime(6) not null, id binary(16) not null, entity_id varchar(255) not null, event_type varchar(255) not null, payload TEXT, primary key (id)) engine=InnoDB;
create table order_item (quantity integer not null, id bigint not null auto_increment, order_id bigint, product_id bigint, primary key (id)) engine=InnoDB;
create table orders (total_amount float(53) not null, id bigint not null auto_increment, order_date datetime(6), user_id bigint, status varchar(255), primary key (id)) engine=InnoDB;
create table payment_order (amount float(53) not null, created_at datetime(6), id bigint not null auto_increment, email varchar(255), name varchar(255), order_id varchar(255), payment_id varchar(255), phone varchar(255), status varchar(255), primary key (id)) engine=InnoDB;
create table product (price float(53) not null, id bigint not null auto_increment, category varchar(255), description varchar(255), image_url varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table user (id bigint not null auto_increment, email varchar(255) not null, name varchar(255) not null, password varchar(255) not null, role varchar(255) not null, primary key (id)) engine=InnoDB;
alter table ai_conversation add constraint UKc6bu39n7lmlefdqgmfh015vnv unique (session_id);
create index idx_cart_user_id on cart (user_id);
create index idx_cart_id on cart_item (cart_id);
create index idx_product_id on cart_item (product_id);
alter table cart_item add constraint uk_cart_product unique (cart_id, product_id);
alter table dead_letter_notification add constraint UK5x6cjric8bn5qvykuy9ewt0ft unique (delivery_id);
alter table g_user_session add constraint UKc9y61nlrun8q1c90l4jnplsy9 unique (refresh_token_hash);
alter table notification_delivery add constraint UK39sede40c348hc3u1k25vm43m unique (event_id, recipient_id, channel);
alter table notification_event add constraint UKjw424bu6xygstmf41aoci69da unique (event_type, entity_id);
alter table ai_conversation add constraint fk_ai_conversation_user foreign key (user_id) references user (id);
alter table ai_conversation_message add constraint FKrrw6u7oociqgrmctmi5oj9jq5 foreign key (conversation_id) references ai_conversation (id);
alter table ai_tool_execution add constraint FKnc3fqsc8folsndob3cmv8kwhn foreign key (conversation_id) references ai_conversation (id);
alter table dead_letter_notification add constraint FKm9fmyuhw8o6juxkmsei4gvdh8 foreign key (delivery_id) references notification_delivery (id);
alter table g_user_session add constraint FKai0vlc3sr5aimmxf46yw63uu0 foreign key (usr_rid) references user (id);
alter table notification_delivery add constraint FKbow3ovamka8ajuqgr10tvgeuc foreign key (event_id) references notification_event (id);
alter table order_item add constraint FKt4dc2r9nbvbujrljv3e23iibt foreign key (order_id) references orders (id);
alter table order_item add constraint FK551losx9j75ss5d6bfsqvijna foreign key (product_id) references product (id);
alter table orders add constraint FKel9kyl84ego2otj2accfd8mr7 foreign key (user_id) references user (id);
