package com.khan.EComm.model;

import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;

@Entity
@Table(
        name = "notification_event",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"event_type", "entity_id"})
        }
)
public class NotificationEvent {

    @Id
    @GeneratedValue
    private UUID id;

    @Column(name = "event_type", nullable = false)
    private String eventType;

    @Column(name = "entity_id", nullable = false)
    private String entityId;

    @Column(columnDefinition = "TEXT")
    private String payload;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt;

    // Required by JPA
    protected NotificationEvent() {
    }

    // Constructor for creating new events
    public NotificationEvent(String eventType, String entityId, String payload) {
        this.eventType = eventType;
        this.entityId = entityId;
        this.payload = payload;
        this.createdAt = Instant.now();
    }

    // --------------------
    // Getters
    // --------------------

    public UUID getId() {
        return id;
    }

    public String getEventType() {
        return eventType;
    }

    public String getEntityId() {
        return entityId;
    }

    public String getPayload() {
        return payload;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    // Intentionally no setter for id (generated by DB)

    public void setPayload(String payload) {
        this.payload = payload;
    }

    // createdAt should never change after creation
}
